# Generated by Django 4.1.3 on 2022-11-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("sheets_count", models.PositiveIntegerField()),
                ("pieces_count", models.PositiveIntegerField()),
            ],
        ),
    ]
