# Generated by Django 4.1.3 on 2022-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0004_unitarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sprintmethod",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
