# Generated by Django 4.1.3 on 2022-11-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0008_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontime",
            name="unit",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="piecework.unit",
            ),
            preserve_default=False,
        ),
    ]
