# Generated by Django 4.1.3 on 2022-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0010_unit_is_finished_alter_action_name_alter_unit_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="bulkheads_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="windows_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="closets_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="rooms_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="washrooms_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
