# Generated by Django 4.1.3 on 2022-11-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0014_alter_sprinttime_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontime",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="piecework.action"
            ),
        ),
        migrations.AlterField(
            model_name="actiontime",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="piecework.unit"
            ),
        ),
    ]
