# Generated by Django 4.1.3 on 2022-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0015_alter_actiontime_action_alter_actiontime_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontime",
            name="is_boarding",
            field=models.BooleanField(default=False),
        ),
    ]
