# Generated by Django 4.1.3 on 2022-11-19 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0016_actiontime_is_boarding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="total_sheets",
        ),
    ]
