# Generated by Django 4.1.3 on 2022-11-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0017_remove_unit_total_sheets"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitSheetCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                ("length", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="piecework.unit",
                    ),
                ),
            ],
        ),
    ]
