# Generated by Django 4.1.3 on 2022-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0018_unitsheetcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
    ]
