# Generated by Django 4.1.3 on 2022-11-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0019_sheettype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitsheetcount",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="piecework.sheettype"
            ),
        ),
    ]
