# Generated by Django 4.1.3 on 2022-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0020_alter_unitsheetcount_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitsheetcount",
            name="length",
            field=models.PositiveIntegerField(
                choices=[(8, 8), (9, 9), (10, 10), (12, 12)]
            ),
        ),
    ]
