# Generated by Django 4.1.3 on 2022-11-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0024_alter_action_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.BooleanField()),
            ],
            options={
                "db_table": "kokolo",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.BooleanField()),
                (
                    "mama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="piecework.test",
                    ),
                ),
            ],
            options={
                "db_table": "kakala",
            },
        ),
    ]
