# Generated by Django 4.1.3 on 2022-11-24 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0027_alter_test_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="test",
            table="makals",
        ),
    ]
