# Generated by Django 4.1.3 on 2022-11-24 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0029_alter_test_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actiontime",
            table="action_times",
        ),
        migrations.AlterModelTable(
            name="sheettype",
            table="sheet_types",
        ),
        migrations.AlterModelTable(
            name="sprintmethod",
            table="sprint_methods",
        ),
        migrations.AlterModelTable(
            name="sprinttime",
            table="sprint_times",
        ),
        migrations.AlterModelTable(
            name="unit",
            table="units",
        ),
        migrations.AlterModelTable(
            name="unitarea",
            table="unit_areas",
        ),
        migrations.AlterModelTable(
            name="unitsheetcount",
            table="unit_sheet_counts",
        ),
        migrations.DeleteModel(
            name="ChildMama",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
