# Generated by Django 4.1.3 on 2023-02-20 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0032_unit_potlights_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActionTime",
            new_name="ActivityTime",
        ),
    ]
