# Generated by Django 4.1.3 on 2023-02-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0034_rename_action_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedUnitsSquareFootage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.SmallIntegerField(blank=True, null=True)),
                ("footage", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "completed_units_square_footage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DailyDurations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "activity_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "db_table": "daily_durations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TotalDurationActivityPerUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.SmallIntegerField(blank=True, null=True)),
                ("activity", models.CharField(blank=True, max_length=20, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
            ],
            options={
                "db_table": "total_duration_activity_per_unit",
                "managed": False,
            },
        ),
    ]
