# Generated by Django 4.1.3 on 2023-10-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0035_completedunitssquarefootage_dailydurations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
            ],
        ),
    ]
