# Generated by Django 4.1.3 on 2023-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0042_alter_activity_table_alter_activitytime_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="note",
            field=models.TextField(),
        ),
    ]
