# Generated by Django 4.1.3 on 2023-10-29 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0043_alter_note_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activitytime",
            old_name="action",
            new_name="activity",
        ),
    ]
