# Generated by Django 4.1.3 on 2023-11-07 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("piecework", "0044_rename_action_activitytime_activity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActivityTime",
            new_name="ActivityLog",
        ),
    ]
