# Generated by Django 4.1.3 on 2023-11-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0045_rename_activitytime_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedUnitsSquareFootage',
        ),
        migrations.DeleteModel(
            name='DailyDurations',
        ),
        migrations.DeleteModel(
            name='TotalDurationActivityPerUnit',
        ),
    ]
