# Generated by Django 4.2.7 on 2024-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('piecework', '0046_delete_completedunitssquarefootage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('drywall_company', models.CharField(blank=True, max_length=255, null=True)),
                ('general_contractor', models.CharField(blank=True, max_length=255, null=True))
            ],
        ),
    ]
