# Generated by Django 4.2.7 on 2024-07-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0047_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='piecework.project'),
        ),
    ]
