# Generated by Django 4.2.7 on 2024-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0047_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drywall_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
