# Generated by Django 4.2.7 on 2024-06-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0048_project_drywall_company_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='general_contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
