# Generated by Django 4.2.7 on 2024-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0048_unit_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
