# Generated by Django 5.1.6 on 2025-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0049_alter_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
