# Generated by Django 4.2.7 on 2024-06-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piecework', '0049_project_general_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='piecework.project'),
            preserve_default=False,
        ),
    ]
