# Generated by Django 4.1.3 on 2022-11-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0002_sprinttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="sprinttime",
            name="method",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="time_tracker.sprintmethod",
            ),
            preserve_default=False,
        ),
    ]
