# Generated by Django 4.1.3 on 2022-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0005_action_description_sprintmethod_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontime",
            name="unit",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
