# Generated by Django 4.1.3 on 2022-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0006_actiontime_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontime",
            name="unit",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
