# Generated by Django 4.1.3 on 2022-11-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0009_alter_actiontime_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="number",
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
