# Generated by Django 4.1.3 on 2022-11-20 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0021_alter_unitsheetcount_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontime",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
