# Generated by Django 4.1.3 on 2022-11-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0025_test_child"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Child",
            new_name="ChildMama",
        ),
    ]
