# Generated by Django 4.1.3 on 2022-11-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0026_rename_child_childmama"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="test",
            table=None,
        ),
    ]
