# Generated by Django 4.1.3 on 2022-11-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0030_alter_actiontime_table_alter_sheettype_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="action",
            table="activities",
        ),
        migrations.AlterModelTable(
            name="actiontime",
            table="activity_times",
        ),
    ]
