# Generated by Django 4.1.3 on 2023-02-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0033_rename_actiontime_activitytime"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Action",
            new_name="Activity",
        ),
    ]
