# Generated by Django 4.1.3 on 2023-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0036_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(help_text='notes for various ideas and reminders'),
        ),
        migrations.DeleteModel(
            name='SprintTime',
        ),
        migrations.DeleteModel(
            name='UnitArea',
        ),
    ]
