# Generated by Django 4.1.3 on 2023-10-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0037_alter_note_note_delete_sprinttime_delete_unitarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitsheetcount",
            name="square_footage",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
