# Generated by Django 4.1.3 on 2023-10-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0038_unitsheetcount_square_footage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SprintMethod",
        ),
    ]
