# Generated by Django 4.1.3 on 2023-10-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0039_delete_sprintmethod"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SheetType",
            new_name="DrywallType",
        ),
    ]
