# Generated by Django 4.1.3 on 2023-10-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0040_rename_sheettype_drywalltype"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="drywalltype",
            table=None,
        ),
    ]
