# Generated by Django 4.1.3 on 2023-10-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_tracker", "0041_alter_drywalltype_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activity",
            table=None,
        ),
        migrations.AlterModelTable(
            name="activitytime",
            table=None,
        ),
        migrations.AlterModelTable(
            name="unit",
            table=None,
        ),
        migrations.AlterModelTable(
            name="unitsheetcount",
            table=None,
        ),
    ]
