# Generated by Django 4.2.7 on 2023-11-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_recurringtasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringTasks',
            new_name='RecurringTask',
        ),
    ]
