# Generated by Django 4.2.7 on 2023-11-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_recurringtasks_recurringtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='time_required',
            field=models.DurationField(null=True),
        ),
    ]
