# Generated by Django 4.2.7 on 2023-11-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_recurringtask_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
