# Generated by Django 4.1.3 on 2023-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_recurringexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
